---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-configmap
  namespace: dev-plt-25-03-2026
data:
  DEMO_MODE: "True"
  DEBUG: "True"
  SERVER_ADDRESS: "http://localhost:5005/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: dev-plt-25-03-2026
  labels:
    app: django
    env: dev
    tier: frontend
spec:
  selector:
    matchLabels:
      app: django
  replicas: 3
  template:
    metadata:
      labels:
        app: django
        env: dev
        tier: frontend
    spec:
      containers:
        - name: django-random
          image: plt/app-rocket-plt-25-03-2026:v1
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: django-app-configmap
            - secretRef:
                name: stripe-secret-plt-25-03-2026
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: dev-plt-25-03-2026
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - port: 5005
      targetPort: 5005
      name: django-np
