---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-configmap
  namespace: dev-plt-25-03-2026
data:
  DEMO_MODE: "True"
  DEBUG: "True"
  SERVER_ADDRESS: "http://localhost:5005/"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: dev-plt-25-03-2026
type: Opaque
stringData:
  STRIPE_PUBLISHABLE_KEY: "pk_test_51T9O1K5wgVagseSW8nTh9DWSlXs5WUghdAhEbipOJeHabowcGpv2l4KCGeZmHvE42eSRJGw30a2kKm61o79xK5iY00Ish9nTgc"
  STRIPE_SECRET_KEY: "sk_test_51T9O1K5wgVagseSWYmkdbIuZ7kQnaQsi3vLR7Rr66stVbZLY8AjQkhtb5uj6LxSoQuYyBkSnojFMunthmkpDE5wE00UTYd3eCT"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: dev-plt-25-03-2026
  labels:
    app: django
    env: dev
    tier: frontend
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
        env: dev
        tier: frontend
    spec:
      containers:
        - name: django-random
          image: soso725/rocketecommerce:beta
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: django-app-configmap
            - secretRef:
                name: stripe-secret
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: dev-plt-25-03-2026
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - port: 5005
      targetPort: 5005
      name: django-np
