apiVersion: v1
data:
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVQ5TzFLNXdnVmFnc2VTVzhuVGg5RFdTbFhzNVdVZ2hkQWhFYmlwT0plSGFib3djR3B2Mmw0S0NHZVptSHZFNDJlU1JKR3czMGEya0ttNjFvNzl4SzVpWTAwSXNoOW5UZ2M=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVQ5TzFLNXdnVmFnc2VTV1lta2RiSXVaN2tRbmFRc2kzdkxSN1JyNjZzdFZiWkxZOEFqUWtodGI1dWo2THhTb1F1WXlCa1Nub2pGTXVudGhta3BERTV3RTAwVVRZZDNlQ1Q=
kind: Secret
metadata:
  name: secret-stripe-plt-25-03-2026
