apiVersion: v1
data:
  DEBUG: VHJ1ZQ==
  DEMO_MODE: VHJ1ZQ==
  EMAIL_HOST: c210cC5nbWFpbC5jb20=
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: NTg3
  EMAIL_USE_TLS: VHJ1ZQ==
  SECRET_KEY: PFNUUk9OR19LRVlfSEVSRT4=
  STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVQ5TzFLNXdnVmFnc2VTVzhuVGg5RFdTbFhzNVdVZ2hkQWhFYmlwT0plSGFib3djR3B2Mmw0S0NHZVptSHZFNDJlU1JKR3czMGEya0ttNjFvNzl4SzVpWTAwSXNoOW5UZ2M=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVQ5
kind: Secret
metadata:
  name: secret-django-plt-25-03-2026
