apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - django-deployment-plt-25-03-2026.yaml
  - stripe-deployment-plt-25-03-2026.yaml
  - django-dashboard-deployment-plt-25-03-2026.yaml